[dev]
  command = "yarn dev" # Command to start your dev server
  targetPort = 3000 # # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on
  publish = "dist" # If you use a _redirect file, provide the path to your static content folder

[build.environment]
  CONTACT_EMAIL = "chris@homecode.co.za"

[context.production.environment]
  CONTACT_EMAIL = "chris@homecode.co.za"